### ISSUE TITLE
Intune App Upload: commitFileFailed

### ISSUE THREAD

**Issue by benbitrise** [pliancy/intune-node#123]
@santese, thank you for this wonderful library 🙏.

When submitting a LOB app, things are failing on the commit step. I think the problem is in my `fileEncryptionInfo`. Would you please share the javascript, if you have it, that creates the `fileEncryptionInfo`? I'd love to reference my code against a working example.

This is my attempt at it, which fails on the commit step.

```
const originalFileBuffer = fs.readFileSync(originalPath);

const key = crypto.randomBytes(32);
const iv = crypto.randomBytes(16);
const encryptor = crypto.createCipheriv('aes-256-cbc', key, iv);

// readFileSync will return a buffer when no encoding option is supplied
let encrypted = encryptor.update(originalFileBuffer);
encrypted = Buffer.concat([encrypted, encryptor.final()])

const hmacKey = crypto.randomBytes(32);
const hmac = crypto.createHmac('sha256', hmacKey);
hmac.update(encrypted)
const hmacHash = hmac.digest();

let encryptedWithHmac = Buffer.concat([hmacHash, iv, encrypted])
fs.writeFileSync(encryptedPath, encryptedWithHmac)

const encryptionInfo = {
        encryptionKey: key.toString('base64'),
        macKey: hmacKey.toString('base64'),
        initializationVector: iv.toString('base64'),
        mac: hmacHash.toString('base64'),
        profileIdentifier: 'ProfileVersion1',
        fileDigest: crypto.createHash('sha256').update(originalFileBuffer).digest('base64'),
        fileDigestAlgorithm: 'SHA256'
};

console.log("***ENCRYPTION INFO***")
console.log(encryptionInfo)

const originalSize = fs.statSync(originalPath).size;
const encryptedSize =  fs.statSync(encryptedPath).size;

console.log(`Original size ${originalSize} and encrypted size ${encryptedSize}`)
```

**Comment by ttfreeman** [comment]
@santese after extracting the file using a Powershell, the upload and initial commit request is successful but when it checks the status of the uploadState, the status is always `commitFileFailed` .

@benbitrise are you using the code above to unencrypt the intunewin file and use it as input to createWin32LobApp()? Have you had a success since creating this issue?

**Comment by ttfreeman** [comment]
Thanks @benbitrise . I will give that `ps1` a try. I will be running the code remotely via API so nodejs would have been ideal but I guess if the ps1 works I can trigger that from nodejs.
